#!/bin/bash -eux
testenv=testenv

rm -rf $testenv
VIRTUALENV_PATH=$testenv ansible_ref_require devel /usr/bin
test -f $testenv/src/ansible/lib/ansible/modules/core/__init__.py
test -f $testenv/src/ansible/lib/ansible/modules/extras/__init__.py
$testenv/bin/ansible --version | grep 2.2
ansible --version | grep 2.2
